autonoleggio/urls.py
from django.urls import path

from autonoleggio import views

app_name = "autonoleggio"

urlpatterns = [
    path("veicoli/", views.VeicoloListView.as_view(), name="lista-veicoli"),
    path(
        "veicolo/<int:pk>/",
        views.VeicoloDetailView.as_view(),
        name="dettaglio-veicolo"
    ),
    path(
        "veicolo/crea/",
        views.VeicoloCreateView.as_view(),
        name="nuovo-veicolo"
    ),
    path(
        "veicolo/<int:pk>/modifica/",
        views.VeicoloUpdateView.as_view(),
        name="modifica-veicolo"
    ),
]

prova_esame/urls.py
from django.contrib import admin
# from django.contrib.auth.views import LoginView
from django.urls import path, include

from prova_esame import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("registrazione/", views.UserRegistrationView.as_view(), name="registration"),
    # path("login/", LoginView.as_view(), name="login"),
    path('autonoleggio/', include('autonoleggio.urls')),
]

autonoleggio/models.py
from django.db import models

TIPI_DI_VEICOLO = [
    ("001", "Automobile"),
    ("002", "Motocicletta"),
    ("003", "Furgone"),
]


class Veicolo(models.Model):
    tipo_di_veicolo = models.CharField(max_length=255, choices=TIPI_DI_VEICOLO)
    numero_di_posti = models.PositiveIntegerField()
    tariffa_giornaliera = models.DecimalField(max_digits=10, decimal_places=2)
    disponibile = models.BooleanField(default=True)

    @property
    def descrizione_tipo_di_veicolo(self):
        return dict(TIPI_DI_VEICOLO).get(self.tipo_di_veicolo)

    def __str__(self):
        return f"{self.descrizione_tipo_di_veicolo} (id: {self.id})"

autonoleggio/forms.py
from django import forms

from autonoleggio.models import Veicolo


class VeicoloForm(forms.ModelForm):
    class Meta:
        model = Veicolo
        fields = (
            'tipo_di_veicolo',
            'numero_di_posti',
            'tariffa_giornaliera',
            'disponibile',
        )
        

autonoleggio/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from autonoleggio.forms import VeicoloForm
from autonoleggio.models import Veicolo


class VeicoloListView(ListView):
    model = Veicolo


class VeicoloDetailView(DetailView):
    model = Veicolo


@method_decorator(login_required, name="dispatch")
class VeicoloCreateView(CreateView):
    model = Veicolo
    form_class = VeicoloForm
    success_url = reverse_lazy("autonoleggio:lista-veicoli")

    template_name = "autonoleggio/veicolo_create.html"


@method_decorator(login_required, name="dispatch")
class VeicoloUpdateView(UpdateView):
    model = Veicolo
    form_class = VeicoloForm
    success_url = reverse_lazy("autonoleggio:lista-veicoli")
    template_name = "autonoleggio/veicolo_update.html"

prova_esame/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class UserRegistrationView(CreateView):
    model = get_user_model()
    form_class = UserCreationForm
    success_url = reverse_lazy("autonoleggio:lista-veicoli")

#    template_name = "autonoleggio/veicolo_create.html"

autonoleggio/templates/autonoleggio/veicolo_create.html
{% extends "base.html" %}

{% block content %}
<h1>Nuovo veicolo</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Invia"></p>
</form>

{% endblock %}

autonoleggio/templates/autonoleggio/veicolo_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Dettaglio del Veicolo: {{ object }}</h1>
    <p>Tipo di veicolo: {{ object.tipo_di_veicolo }}</p>
    <p>Numero di posti: {{ object.numero_di_posti }}</p>
    <p>Tariffa giornaliera: {{ object.tariffa_giornaliera }}</p>
    <p>Disponibile: {{ object.disponibile }}</p>
{% endblock %}

autonoleggio/templates/autonoleggio/veicolo_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Lista di Veicoli</h1>
    {% if object_list %}
        <ul>
            {% for obj in object_list %}
                <li>
                    {{ obj }}:
                    <a href="{% url 'autonoleggio:dettaglio-veicolo' obj.id %}">
                        Visualizza dettaglio
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

autonoleggio/templates/autonoleggio/veicolo_update.html
{% extends "base.html" %}

{% block content %}
<h1>Modifica veicolo: {{ object }}</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit" value="Invia"></p>
</form>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <style>
        body{
            background-color: lightgray;
        }
        nav{
            background-color: lightblue;
            padding: 1rem 0;
        }
        nav a {
            padding: 1rem;
        }
    </style>
</head>
<body>
<nav class="navbar">
    <a class="navbar-item" href="{% url 'autonoleggio:lista-veicoli' %}">Lista veicoli</a>
</nav>
<main class="container">
    {% block content %}{% endblock %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>

</body>
</html>